### ISSUE TITLE
HELPPP

### ISSUE THREAD

**Issue by katz0018** [katz0018/portfolio#1]
@thomasjbradley

I broke something in my website, how do I pull the last request ?

**Comment by thomasjbradley** [comment]
If you go to this page, can you see the changes that broke your website?
https://github.com/katz0018/portfolio/commits/master

**Comment by katz0018** [comment]
I can not figure it :( , but I want to go back the state of when I last committed , how do I do this? does it say somewhere on learn the web?

**Comment by katz0018** [comment]
nvm, I did it I think :)
